### ISSUE TITLE
About ICFG-PEDES dataset

### ISSUE THREAD

**Issue by ljwwwiop** [anosorae/IRRA#1]
Hi, I'm experiencing a memory shortage problem doing validation operations while training the ICFG-PEDES dataset, I'm using 12G of TITAN and have the training batch size set to 32 and the test batch size set to 128, but it seems that there is still a GPU memory shortage problem.
I checked the training logs and found that there seems to be no val dataset, which seems to be the cause of the memory shortage. So I'm asking if the ICFG-PEDES data has a validation dataset loaded, or rather a json file of the cut data?

Thank you very much for open sourcing the code and I look forward to seeing the correct link to your paper, thanks!

**Comment by ljwwwiop** [comment]
![image](https://user-images.githubusercontent.com/45536607/225940778-054a50f3-3bb0-4dfa-bbb7-244ca82edcd2.png)

**Comment by anosorae** [comment]
The SSAN author divided ICFG-PEDES into a training set and a testing set: the former comprises 34,674 image-text pairs of 3,102 persons, while the latter contains 19,848 image-text pairs for the remaining 1,000 persons. There is no val set for ICFG-PEDES datasets.

For the GPU memory shotage, I suggest you to further reduce the batchsize.

**Comment by anosorae** [comment]
And the correct link to our paper will be update after the camera-ready deadline of CVPR 2023, thank you for your attention to our work. @ljwwwiop

**Comment by ljwwwiop** [comment]
> 

Thank you very much, I switched to 32G GPU and trained fine.

**Comment by womeizhaol** [comment]
> Hi, I'm experiencing a memory shortage problem doing validation operations while training the ICFG-PEDES dataset, I'm using 12G of TITAN and have the training batch size set to 32 and the test batch size set to 128, but it seems that there is still a GPU memory shortage problem. I checked the training logs and found that there seems to be no val dataset, which seems to be the cause of the memory shortage. So I'm asking if the ICFG-PEDES data has a validation dataset loaded, or rather a json file of the cut data?
> 
> Thank you very much for open sourcing the code and I look forward to seeing the correct link to your paper, thanks!

请问能分享一下CUHK-PEDES和ICFG-PEDES数据集吗，万分感谢

**Comment by duanmin940-del** [comment]
> > 您好，我在训练 ICFG-PEDES 数据集时遇到了验证操作的内存不足问题。我使用的是 12G 的 TITAN 显存，训练批次大小设置为 32，测试批次大小设置为 128，但似乎仍然存在 GPU 内存不足的问题。我查看了训练日志，发现似乎没有加载验证数据集，这可能是导致内存不足的原因。所以我想请问一下，ICFG-PEDES 数据集是否加载了验证数据集，或者是否加载了包含切割数据的 JSON 文件？
> > 非常感谢您开源代码，期待看到您论文的正确链接，谢谢！
> 
> 请问能否分享一下CUHK-PEDES和ICFG-PEDES数据集吗，万分感谢

请问能否分享一下CUHK-PEDES和ICFG-PEDES数据集吗，我的邮箱是3132564840@qq.com
