### ISSUE TITLE
Missing resize_text_pos_embed in clip_model.py

### ISSUE THREAD

**Issue by AwePhD** [anosorae/IRRA#10]
Hello,

It seems that the method [resize_text_pos_embed](https://github.com/anosorae/IRRA/search?q=resize_text_pos_embed) is missing in your [CLIP model](https://github.com/anosorae/IRRA/blob/91a685661a3a2c34c37666d655e1b352a5e92600/model/clip_model.py#L458). Can you provide it, please ?
Or maybe it's some dead code left because we never enter in this condition? 

Thanks again for your time and your hard work for this paper.
Mathias.

**Comment by anosorae** [comment]
resize_text_pos_embed is a method to adjust the CLIP model text embedding, it is only called when you need to change the default 77 maximum text sequence length, in the IRRA framework, we do not change the maximum text sequence length, so this method will not be called.

**Comment by AwePhD** [comment]
Thanks!
