### ISSUE TITLE
Confusion about caption tokens and mlm tokens when using mlm

### ISSUE THREAD

**Issue by lzfff12** [anosorae/IRRA#13]
In the data processing part, we found that when using mlm, the caption tokens after processing are the same as mlm tokens, but this is different from the description in the paper

**Comment by anosorae** [comment]
Please give a more detailed evidence to prove your claim.

**Comment by lzfff12** [comment]
![image](https://user-images.githubusercontent.com/55379485/231056609-51fbd214-513b-4ba7-ae97-a1600d922605.png)
The caption_tokens in the diagram are a list that is passed directly to the function, and if the value in the function changes, the value in the list will also change

**Comment by lzfff12** [comment]
We also confirmed this by printing

**Comment by anosorae** [comment]
I have confirmed the issue you mentioned, which was caused by an oversight in my code writing, and I am evaluating the impact of this issue on the final retrieval results.

Anyway, thank you for pointing this out, I will provide more explanation after the evaluation.

**Comment by lzfff12** [comment]
OK，thanks

**Comment by Zplusdragon** [comment]
The two list share the same memory. This may be the reason. Turning to use deepcopy will solve it. However, will it affect the performance?

**Comment by anosorae** [comment]
When I changed the shallow copy to a deep copy, i.e. calculating the SDM loss between image feature and masked text feature, there was some performance loss. Here are the results:
| task |   R1   |   R5   |  R10   |  mAP   |  mINP  |
|------|------|-------|--------|--------|--------|
| t2i  | 71.069 | 87.606 | 92.122 | 64.879 | 50.267 |

And when I calculate the SDM loss bwtween image feature and masked text feature and  text feature, the performance loss is lower:
| task |   R1   |   R5   |  R10   |  mAP   |  mINP  |
|------|------|-------|--------|--------|--------|
| t2i  | 72.840 | 88.678 | 93.324 | 65.407 | 49.512 |

From my point of view, I think the question raised in this issue about using a shallow copy and not a deep copy is equivalent to the fact that I have applied an augmentation to the input text, similar to the data augmentation done to the input image. This leads to a difference in the final result. **But it does not affect the conclusions of the paper.**
Thank you for your attention to our work, I hope that my response will satisfy you.

**Comment by lzfff12** [comment]
Is the result of the above table under the setting of id+mlm+sdm？

**Comment by anosorae** [comment]
Yes. @lzfff12

**Comment by Zplusdragon** [comment]
In the build_random_masked_tokens_and_labels function, there is no deepcopy operation on caption_tokens to get the mlm_tokens. And this will make the two tokens completely same. It means the caption_tokens using for calculating SDM_loss are also masked. But in the paper, it uses unmasked caption_tokens to calculate it. Maybe is it a bug?

**Comment by anosorae** [comment]
@Zplusdragon  When I was writing the code, I thought the .numpy() function would convert from tensor to a new ndarray, not realising that the two would actually share memory. So, you could say it's a bug.
