### ISSUE TITLE
The accuracy of IDLoss experiment is much lower than 65.33% of the paper

### ISSUE THREAD

**Issue by xie-xue** [anosorae/IRRA#16]
parameter
 loss_names='id'
 lr=1e-05
 lr_factor=5.0
Concrete result
![image](https://user-images.githubusercontent.com/80504432/233601860-982732f3-e7b4-482f-98a6-41cfced5f2cb.png)
Looking forward to your reply！

**Comment by anosorae** [comment]
The id loss in the table is not a separate loss, but is trained jointly with the itc loss in the baseline.

**Comment by xie-xue** [comment]
Thank you
