### ISSUE TITLE
About using RN50 as image encoder

### ISSUE THREAD

**Issue by sunmenmian** [anosorae/IRRA#18]
Hello, thanks for your good paper.  And how can I run this code with resnet50 pre-trained weights?
<img width="630" alt="image" src="https://user-images.githubusercontent.com/66548053/234320119-86e94b1b-cfad-4ab7-b492-10a533a56cc3.png">

**Comment by anosorae** [comment]
Comment out this line of code and uncomment the next line of code for this line. i.e. [L84](https://github.com/anosorae/IRRA/blob/8b5af4d49819b08ec2d2a3148df71c8b81679650/model/build.py#L84) and [L97](https://github.com/anosorae/IRRA/blob/8b5af4d49819b08ec2d2a3148df71c8b81679650/model/build.py#L97)
