### ISSUE TITLE
KeyError: 'mlm_ids'

### ISSUE THREAD

**Issue by yangmengmeng123** [anosorae/IRRA#27]
When I run train.py, the following error appears:

Traceback (most recent call last):
  File "f:\Workspace\0research0\IRRA-main\train.py", line 77, in <module>
    do_train(start_epoch, args, model, train_loader, evaluator, optimizer, scheduler, checkpointer)    
  File "f:\Workspace\0research0\IRRA-main\processor\processor.py", line 50, in do_train
    ret = model(batch)
          ^^^^^^^^^^^^
  File "F:\env\pytorch\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl 
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\env\pytorch\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\Workspace\0research0\IRRA-main\model\build.py", line 126, in forward
    mlm_ids = batch['mlm_ids']
              ~~~~~^^^^^^^^^^^
KeyError: 'mlm_ids'

**Comment by hanjx520** [comment]
> When I run train.py, the following error appears:
> 
> Traceback (most recent call last): File "f:\Workspace\0research0\IRRA-main\train.py", line 77, in do_train(start_epoch, args, model, train_loader, evaluator, optimizer, scheduler, checkpointer) File "f:\Workspace\0research0\IRRA-main\processor\processor.py", line 50, in do_train ret = model(batch) ^^^^^^^^^^^^ File "F:\env\pytorch\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\env\pytorch\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "f:\Workspace\0research0\IRRA-main\model\build.py", line 126, in forward mlm_ids = batch['mlm_ids'] ~~~~~^^^^^^^^^^^ KeyError: 'mlm_ids'

Has this problem been solved now

**Comment by HommeJK** [comment]
I have the same problem, how can I solve it?

**Comment by John-Smith-study** [comment]
I also face this similar problem, I  want to know whether you solve this problem？ if you solve this problem ,please share this question to me. my email is 2823672596@qq.com. thank you!
