### ISSUE TITLE
文本全局特征如何获得？

### ISSUE THREAD

**Issue by shams2023** [anosorae/IRRA#28]
t_feats = text_feats[torch.arange(text_feats.shape[0]), caption_ids.argmax(dim=-1)].float()
和你文中的描述似乎并不一致，请问你代码中的这部分，该如何理解，选择的是文本的那部分作为文本的全局特征的？
谢谢1

**Comment by anosorae** [comment]
请说出哪里不一致，这行代码从GPT到CLIP全是这么写的，都是选择EOS作为全局特征

**Comment by shams2023** [comment]
那就没问题了 如果选择的是eos 就没问题了 谢谢回复

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月26日 10:56 |
| 收件人 | anosorae/IRRA ***@***.***> |
| 抄送人 | shams2023 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [anosorae/IRRA] 文本全局特征如何获得？ (Issue #28) |

请说出哪里不一致，这行代码从GPT到CLIP全是这么写的，都是选择EOS作为全局特征

**Comment by womeizhaol** [comment]
> 那就没问题了 如果选择的是eos 就没问题了 谢谢回复
> […](#)

请问能分享一下CUHK-PEDES和ICFG-PEDES数据集吗，万分感谢
