### ISSUE TITLE
A small multi GPU training bug

### ISSUE THREAD

**Issue by Aotle** [anosorae/IRRA#5]
It's on lines 98-100 of [IRRA](https://github.com/anosorae/IRRA)/[processor](https://github.com/anosorae/IRRA/tree/main/processor)/processor.py
```
if args.distributed: 
     top1 = evaluator.eval(model.module.eval())
else:
     top1 = evaluator.eval(model.eval())
```

**Comment by anosorae** [comment]
Thank you for pointing out this issue.

**Comment by Aotle** [comment]
lines 108 of [IRRA](https://github.com/anosorae/IRRA)/[processor](https://github.com/anosorae/IRRA/tree/main/processor)/processor.py
```
if get_rank() == 0:
    logger.info(f"best R1: {best_top1} at epoch {arguments['epoch']}")
```

**Comment by anosorae** [comment]
We have only used a single GPU in our experiments and have not verified the validity of the multi-GPU training code, so we cannot guarantee its reliability if you want to train with DDP.

Anyway, you are welcome to keep submitting bugs about multi GPU training and we will fix it as soon as possible.

**Comment by Pefect96** [comment]
> lines 108 of [IRRA](https://github.com/anosorae/IRRA)/[processor](https://github.com/anosorae/IRRA/tree/main/processor)/processor.py
> 
> ```
> if get_rank() == 0:
>     logger.info(f"best R1: {best_top1} at epoch {arguments['epoch']}")
> ```

I want to know if the multi GPU training is work?
