### ISSUE TITLE
cant use best.pth

### ISSUE THREAD

**Issue by Justhuayu** [anosorae/IRRA#7]
File "C:\Users\14439\Documents\Code\Pycharm\IRRA-main\utils\checkpoint.py", line 150, in load_state_dict
    model.load_state_dict(model_state_dict,strict=False)
  File "C:\Users\14439\Documents\Jetbrains\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for IRRA:
	size mismatch for classifier.weight: copying a param with shape torch.Size([3701, 512]) from checkpoint, the shape in current model is torch.Size([11003, 512]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([3701]) from checkpoint, the shape in current model is torch.Size([11003]).

**Comment by Justhuayu** [comment]
I have solved this problem,in  test.py file
change "model = build_model(args)" to  model = build_model(args,num_classes=3701)

**Comment by anosorae** [comment]
Thank for pointing this out, I have fixed the bug.
