### ISSUE TITLE
Code for straight forward CLIP fine-tuned to PEDES

### ISSUE THREAD

**Issue by AwePhD** [anosorae/IRRA#8]
Hello, 

Good job, your paper is very interesting. I am happy to see papers leveraging VLP for Text ReID.

I am interested to have the fine-tuned CLIP model on PEDES. Do you plan to share the training script and/or the weights of this model, please ? I can re-do it by my own but it would save some times for me (and some other people, probably). 

Thanks again for the contribution to the community.

**Comment by anosorae** [comment]
You can get the straight forward CLIP fine-tuned results by  the following training config:
```python
python train.py \
--name CLIP_finetune \
--img_aug \
--batch_size 64 \
--loss_names 'itc' \
--dataset_name 'CUHK-PEDES' \
--root_dir 'your dataset root dir' \
--num_epoch 60
```

**Comment by AwePhD** [comment]
Thanks you for your quick and useful answer. It's valuable!
