### ISSUE TITLE
关于id_loss在训练过程中不收敛的问题

### ISSUE THREAD

**Issue by Zplusdragon** [anosorae/IRRA#9]
您好，我按照您所提供的代码在单张3090跑了训练，但是在logging日志中发现id_loss并没有收敛，最终一直维持在7.847左右，请问这是什么原因呢？

**Comment by anosorae** [comment]
如果你想要让id_loss继续下降，可以在这里的代码：
https://github.com/anosorae/IRRA/blob/91a685661a3a2c34c37666d655e1b352a5e92600/solver/build.py#L23
对classifier的学习率进行调整，如果你调大学习率的话，id_loss会下降得更快且能收敛到你想要的值，但是会对最终检索结果造成一定的影响，这需要你自己进行实验来找出更合适的学习率设置。
